README.md
root.tf

Add common tag for CostCentre so that Digital Services can identify our resources in the organisation's AWS bill.
Also add a note to the README to make it clearer that these Terraform scripts need to be run from a dev machine.

 Add CostCentre tag to all resources 

---

modules/specific-environment-permissions/environment_permissions.tf

The role which the deployment containers use to deploy to ECS was
missing the policy which actually allows it to assume the role which
allows it to deploy, so none of the deployments were working. This puts
it back.

Add policy to role.

---

modules/environment-roles/templates/app_base_terraform_policy.json.tpl

I can't create a new S3 bucket with flow logs when the flow log
permissions already exist because it's missing this from the policy. This adds it
in.

Add create policy version action

---

modules/environment-roles/root.tf
modules/environment-roles/templates/app_base_terraform_policy.json.tpl
modules/environment-roles/templates/tdr_jenkins_read_params.json.tpl

Additional Keycloak client added to update TDR realm configuration
New Keycloak client uses client secret
Client secret needs to be set in each TDR environment via Terraform role and read by Jenkins job to update the configuration

New Keycloak client secret

---

modules/environment-roles/root.tf
modules/environment-roles/templates/app_base_terraform_policy.json.tpl
modules/environment-roles/templates/shared_terraform_policy_2.json.tpl
modules/environment-roles/templates/shared_terraform_policy_3.json.tpl

There are permissions to access the new download files lambda. There's a
couple of other bits I noticed while I was doing it which I've lumped in
together.
Jenkins didn't have access to the file format build roles. I've no idea
how this used to work but it does now.
There was a permission missing that stopped us changing the mount target
security groups, I've added it in.

Mostly permissions for the download lambda.

---

modules/environment-roles/root.tf

Jenkins needs permission to update the download files lambda to run the deploy job correctly

Permission to update download files lambda

---

root.tf

We are using healthcheck io to check the Jenkins build is running which
means the backup script needs to know what it is.
We can't make it public so I've stored it in parameter store and added
it as an argument to the command.

Add healthcheck url to argument

---

root.tf

This is being moved to the tdr-jenkins repository. Configuring it in this repository caused a problem whenever the Jenkins EC2 instance was redeployed, because the maintenance window is linked directly to
the EC2 _instance_ ID. This meant that when you deploy the Jenkins EC2 instance, the backups fail because the maintenance windows tries to run the backups on the old instance.
Moving the configuration to the tdr-jenkins repo should fix the issue because we deploy a new EC2 instance by running the tdr-jenkins Terraform script. This should update link between the maintenance window and the EC2 instance whenever we deploy a new instance.

Remove Jenkins backup configuration

---

modules/environment-roles/templates/shared_terraform_policy_2.json.tpl

Account number misidentified
SSM param name changed for account number to reflect what account number it is.

Renamed ssm param

---

modules/environment-roles/root.tf

This is the role Jenkins assumes to deploy the authoriser lambda. I
missed the permission that allows it to do that.

Add permission for export api authoriser

---

root.tf

Run ECR image scans every 7 days instead of every 2 days to reduce noise from low-priority results over Christmas.
The service is not running in production yet, so it's OK if we don't get scan notifications as quickly right now.

Temporarily reduce image scan frequency

---

root.tf

The ECR module adds this URL to an AWS tag on the ECR repo, to make it easier to find the Docker image source.

Add link from each ECR repo to image Dockerfile

---

modules/permissions/templates/jenkins_lambda_deploy_policy.json.tpl
root.tf

The lambda module is no longer just doing ecr scans so I've renamed it. I've also added in the jenkins maintenance window event which is defined in the jenkins project. It's hard coded because there's no terraform data block for cloudwatch events.

Rename the lambda

---

root.tf

These sns topic arns are used inside the notifications lambda module to add permissions for these sns topics to invoke the lambda function.
The idea being that we will have one sns topic each for intg, staging and prod and these 3 will all connect to the notifications lambda in the management account. The arns are hardcoded because terraform doesn't have permissions to get them using a data block.

Add sns topic arns to the lambda module.

---

modules/permissions/common_permissions.tf
modules/permissions/templates/jenkins_check_ami_policy.json.tpl

The s3 permissions are needed to access the terraform state file to get the current ami and the describe image permissions are to get the latest one.

Add a policy for Jenkins to check ami version.

---

modules/environment-roles/templates/shared_terraform_policy_4.json.tpl

This is the policy which is attached to the api ecs task role to allow
it to use iam auth on the db.

Add new API policy

---

.gitignore
README.md
root.tf

These are CVEs for which no fix is available, and which should be temporarily muted in the email and Slack alerts.
Need to merge two other PRs before this one:

Pass list of muted ECR alerts to notifications lambda 

---

modules/permissions/templates/jenkins_lambda_deploy_policy.json.tpl

Fix the broken ECR scan deployment job on Jenkins, which did not have permission to deploy the ECR scan lambda.

Allow lambda deployment jobs to deploy ECR scan lambda

---

modules/environment-roles/templates/app_base_terraform_policy.json.tpl
modules/environment-roles/templates/shared_terraform_policy_1.json.tpl

We've never actually used any load balancer rules, we've just used the default target. These permissions are needed now from the changes to keycloak's load balancer to only allow requests with the same host as itself.

Add permissions to create, delete and describe rules.

---

root.tf

This mandatory parameter was added to the Cloudwatch logs module in a recent commit: https://github.com/nationalarchives/tdr-terraform-modules/commit/1f83113721cc65193716b21d63ca5e6a9c7edfea

Add missing common_tags parameter

---

modules/environment-roles/root.tf
modules/environment-roles/templates/app_base_terraform_policy.json.tpl
modules/environment-roles/templates/app_base_terraform_ssm_parameters_policy.json.tpl
modules/environment-roles/templates/shared_terraform_policy_4.json.tpl
root.tf

This includes permissions for terraform to create the lambdas and
changes to allow the lambdas to be created in the environments with the
correct permissions.

Updates for environment notifications.

---

modules/environment-roles/templates/shared_terraform_policy_2.json.tpl

These parameters are no longer used. The Terraform scripts which used to use them are now using the IP list in tdr-configurations instead, so these parameters will be deleted.

Remove parameter store params which list trusted IPs

---

root.tf

Add `TerraformSource` tag which links to this code repo. This will make it easier for devs to find the Terraform source which created a particular resource in the AWS console.

Add new default tag for Terraform source

---

modules/environment-roles/root.tf
modules/environment-roles/templates/run_ec2_describe.json.tpl

This is the role and policy which allows the job which checks the age of
a bastion and delete it if it is too old. The problem was that I had it
in the terraform for the bastion creation in the tdr-scripts project so
we could only check if the bastion was too old if it had already been
created which is less than ideal.
So these roles need to exist permanently so I've added them in here.

Move describe ec2 role from tdr-scripts terraform.

---

modules/environment-roles/templates/terraform_scripts_policy.json.tpl

This is for the bastion creation script to assume the roles it needs.
Upgraded Terraform is now using this API call.

Add ListRolePolicies permission.

---

modules/environment-roles/root.tf
modules/environment-roles/templates/shared_terraform_policy_4.json.tpl
modules/grafana/root.tf

We're going to use the athena module in `tdr-terraform-modules` to
create athena work groups and named queries and these allow us to do it.
The glue permissions oddly are necessary.
https://docs.aws.amazon.com/athena/latest/ug/fine-grained-access-to-glue-resources.html#access-to-glue-resources-limitations

Add permissions for creating athena workgroups

---

modules/environment-roles/root.tf
modules/environment-roles/templates/app_base_terraform_policy.json.tpl
modules/environment-roles/templates/shared_terraform_policy_4.json.tpl
modules/environment-roles/templates/shared_terraform_policy_5.json.tpl

These are the new permissions needed by terraform in order to set up the new Cloudfront proxy, the API gateway and the new Lambda.

Permissions for terraform to setup Cloudfront proxy

---

modules/environment-roles/root.tf

This is the Jenkins lambda role which needs permission to deploy the new
signed cookies lambda.

Add permission to deploy signed cookies lambda.

---

modules/specific-environment-permissions/environment_permissions.tf

The role is the one used to run the e2e tests. I've moved the read
params section into the main transfer-frontend image to speed things up
a bit so that role needs permissions to get the parameters.

Add read params policy to node s3 role.

---

modules/environment-roles/templates/shared_iam_terraform_policy.json.tpl

Changes already deployed
AWS accounts Terraform requires access to the IAM support group

Missing permission to access the IAM support group

---

.terraform.lock.hcl
root.tf

These secrets don't change in different environments so they can be
added at the GitHub repository level rather than the environment level.

Add common secrets to repositories

---

.github/workflows/check.yml
modules/specific-environment-permissions/outputs.tf
root_github.tf
templates/iam_policy/github_cloudwatch_policy.json.tpl

This is:
* Roles to run terraform from GitHub actions
* Log groups to write the terraform plan logs to
* Secrets for the terraform environment and modules repos.

Add repository permissions and logs for terraform GitHub actions.

---

root_github.tf

The GitHub release summary is committing to the repository so it needs
gpg to sign the commits.

Add GPG secrets.

---

root_github.tf

The staging and prod roles were still restricted to repositories
starting with tdr-terraform-* which is unhelpful when running terraform
in tdr-scripts. I've updated this to match what's in integration.

Fix the terraform role permissions.

---

root_github.tf

The reason for the role change is so I can use the existing reusable
workflow to deploy to the management account.

Add notifications lambda resources.

---

modules/environment-roles/root.tf
modules/environment-roles/templates/github_service_unavailable_deploy_policy.json.tpl
root_github.tf

- Add the secrets in for the repository.
- Duplicate the existing Jenkins role to modify the ALB so GitHub actions can assume it. The old role can be removed later.

Service unavailable changes.

---

root_data.tf
root_github.tf

This means that the bastion notifications and the release summary will
now go to da-tdr-notifications.

Update SLACK_WEBHOOK for tdr-scripts.

---

modules/environment-roles/templates/shared_terraform_policy_1.json.tpl

This is for adding cloudwatch events so we can schedule lambdas.

Add events permissions.

---

root_github.tf

The policy on the SSM parameters is set to alert on no change so the
type in the event bridge rule needs to be NoChangeNotification.

Change event bridge policy type

---

.terraform.lock.hcl
modules/environment-roles/templates/shared_terraform_policy_1.json.tpl

I've updated the AWS provider in tdr-terraform-environments and it's now making this new API call that it wasn't before so we need two more permissions. There is an [AWS blog post](https://aws.amazon.com/blogs/aws/easily-manage-security-group-rules-with-the-new-security-group-rule-id/) about it.
It's also updated the lock file in this project, I don't know why.

Add missing terraform permission.

---

root.tf

This was used to install Droid on EFS. We're not doing that any more so
this can go.

Remove the front end build ECR repository.

---

root_github.tf

The terraform role is mostly used by terraform which can access the
global parameters directly but there is one python script in
tdr-aws-accounts which needs it and it's difficult to get it from
terraform so I'm adding it in here.

Add external ID to secrets.

---

.gitmodules
.terraform.lock.hcl
root_github.tf

This uses the new da-terraform-configurations repo.
This is pointing to a branch on that repo so it will need to be updated
later but this is ready for review.
I've changed the custodian and aws-accounts jobs to be more generic but
now we need a lot of project and environment specific secrets so this
adds them in.

Add config for custodian and aws-accounts.

---

modules/environment-roles/templates/terraform_scripts_policy.json.tpl

Latest version of aws provider appears to require wider set of permissions to create ec2 instance and security groups
Give scripts role complete ec2 permissions

Provide scripts role with wider ec2 permissions

---

root_github.tf

Requires PR: https://github.com/nationalarchives/tdr-terraform-github/pull/4
Remove tdr-reporting and tdr-keycloak-user-management configurations as we have migrated to new tdr-terraform-github repo

Remove tdr-reporting and tdr-keycloak-user-management configurations

---

modules/environment-roles/templates/shared_terraform_policy_1.json.tpl

TDR is hosting the reference generator service which need dynamodb resources

Terraform roles dynamodb permissions

---

root.tf

Requires PR: https://github.com/nationalarchives/tdr-terraform-modules/pull/257
Value in policy needs to be an arn or wildcard
Instead have separate IAM policy for s3 bucket KMS key permissions and don't apply to mgmt version of notifications lambda

Place holder value causes error

---

root_github.tf

Requires PR: https://github.com/nationalarchives/tdr-terraform-github/pull/16
Cloudwatch event and SSM parameter moved to 'tdr-terraform-github' repository

Remove cloud watch event on PAT expiry

---

modules/permissions/common_permissions.tf

At least the reference generator repo is using this role to deploy in the github action.  To use the S3 lockfile in TF, it needs to be able to delete the S3 lockfile to release the lock.  Have deployed and is working e.g here it work https://github.com/nationalarchives/da-reference-generator/actions/runs/16032710727
here where it doesn't have the permission and then fails
https://github.com/nationalarchives/da-reference-generator/actions/runs/16030799032/job/45230609785

Tdrd 825/allow terraform deploy role to delete s3 terraform lock files
