nationalarchives/tdr-terraform-backend

modules/environment-roles/templates/shared_terraform_policy.json.tpl

required to eliminate error in terraform plans

permissions to list route53 tags

---

modules/environment-roles/templates/shared_terraform_policy.json.tpl

permissions for KMS

---

modules/environment-roles/templates/shared_terraform_policy_2.json.tpl

Add permissions for Security Hub

Security Hub

---

modules/environment-roles/templates/shared_terraform_policy_1.json.tpl
modules/environment-roles/templates/shared_terraform_policy_2.json.tpl
modules/environment-roles/templates/shared_terraform_policy_3.json.tpl

Permissions for Terraform deployment of log aggregation lambda, IAM and SNS deployment

Permissions for log aggregation deployment

---

modules/environment-roles/root.tf
modules/environment-roles/templates/app_base_terraform_policy.json.tpl
modules/environment-roles/templates/shared_terraform_policy_1.json.tpl
modules/environment-roles/templates/shared_terraform_policy_2.json.tpl

There is a role which jenkins uses for updating lambdas. I've added the
new back end check permissions to the list.

Update the Jenkins lambda update role.

---

modules/environment-roles/templates/app_base_terraform_policy.json.tpl
modules/environment-roles/templates/tdr_jenkins_read_params.json.tpl

New ssm parameter for keycloak configuration properties.
Permission for Jenkins to set and read new ssm parameter

Add permission for new ssm parameter

---

modules/environment-roles/templates/app_base_terraform_policy.json.tpl
modules/environment-roles/templates/tdr_jenkins_read_params.json.tpl

Permission for Jenkins to set and read new ssm parameter for administration of Keycloak users in TDR realm

New ssm parameter for end to end test

---

modules/environment-roles/root.tf
modules/environment-roles/templates/app_base_terraform_policy.json.tpl
modules/environment-roles/templates/app_base_terraform_ssm_parameters_policy.json.tpl
modules/environment-roles/templates/shared_terraform_policy_4.json.tpl
modules/environment-roles/templates/tdr_jenkins_read_params.json.tpl

- Add permissions to deploy create keycloak user lambda
- Add permissions for ssm parameter for the keycloak user password
- Put the permission in the right place

Add create keycloak user lambda

---

modules/environment-roles/templates/shared_iam_terraform_policy.json.tpl
modules/environment-roles/templates/shared_terraform_policy_1.json.tpl

Tdr 1188 update aws account permissions

---

modules/environment-roles/root.tf
modules/environment-roles/templates/shared_terraform_policy_1.json.tpl
modules/specific-environment-permissions/environment_permissions.tf

I've already deployed terraform environments removing the old waf
regional stuff and adding in the waf v2 changes so this swap will work.

Add WAFV2 permissions.

---

root_github.tf

Adds the non environment specific secrets needed by the tdr-checksum repo

Add secrets for tdr-checksum repo

---

root_github.tf

This is needed for checking out the configurations repo and running the
deploy job.

Add workflow access token secret.

---

root_data.tf
root_github.tf

Some of these will conflict with the other PRs but I can sort that out
later

Add secrets for auth utils deploy to maven.

---

root_github.tf

This repo is a lambda as well as a library so needs the
MANAGEMENT_ACCOUNT variable.

Add management account.

---

root_github.tf

- Add backend check performance secrets
- Allow all tdr- repos to use this role
- Add role to run terraform on sandbox
- Add ssm read only policy

Add backend performance secrets

---

root_github.tf

- Add secrets for tdr-scripts repo

Add tdr scripts secrets

---

modules/environment-roles/root.tf
modules/environment-roles/templates/custodian_policy.json.tpl
modules/environment-roles/templates/github_assume_role.json.tpl
modules/environment-roles/templates/jenkins_lambda_policy.json.tpl
root_github.tf
templates/iam_role/github_assume_role.json.tpl

Permissions for tdr-create-db-users
Permissions for tna-custodian plus some new roles.

Multiple repository changes for GitHub actions

---

root_github.tf

They only need the slack webhook to alert if secrets are found

Add permissions for the documentation repos.

---

.terraform.lock.hcl
root.tf

- Create kms management key.
- Update terraform-modules commit hash

Create KMS mgmt key

---

root_github.tf

Also update the submodules hashes

Add outside collaborators parameter.

---

Jenkinsfile-check
README.md
versions.tf

Requires PR: https://github.com/nationalarchives/tdr-github-actions/pull/34

Upgrade Terraform to 'v1.3.2'

---

Jenkinsfile-check
README.md
versions.tf

Upgrade Terraform version and general tidy up

---

root_github.tf

These are the secrets for the new tdr-components repository.
Also, update the two submodule hashes.

Add tdr-components repository

---

root.tf
root_data.tf
root_github.tf

Add a cloudwatch_events to notify that the GitHub token for the tna-digital-archiving-jenkins user is going to expire and needs to update with a new one

TDR-2476 - Rotate github token

---

.terraform.lock.hcl
versions.tf

Required to support github dependabot secrets

Upgrade github provider to latest version

---

modules/environment-roles/templates/shared_iam_terraform_policy.json.tpl

Permission to access iam user credentials policy

---

root_github.tf

Already deployed
File format repository now generates automate release bump PRs so needs to sign the commits

Add gpg passphrase and private key secrets

---

modules/state-lock/dynamodb.tf
modules/state/output.tf
modules/state/s3.tf

Tdr 2488 GitHub terraform backend

---

modules/environment-roles/root.tf
modules/environment-roles/templates/github_assume_role.json.tpl
modules/environment-roles/variables.tf
root.tf
root_github.tf
templates/iam_role/github_assume_role.json.tpl

Replace wild card with actual repository names
Required: https://github.com/nationalarchives/tdr-configurations/pull/175

TDRD-261 - Replace wild card with actual repository names

---

modules/environment-roles/root.tf
modules/environment-roles/templates/shared_iam_terraform_policy.json.tpl
modules/environment-roles/templates/shared_iam_terraform_policy_1.json.tpl
root.tf

Transfer service ecs terraform permissions

---

.terraform.lock.hcl
root.tf

Allow Staging transfer service execution role to pull image from ECR

ECR permissions for transfer service staging

---

modules/environment-roles/templates/shared_iam_terraform_policy_1.json.tpl

Permissions for creation of new IAM policies

---

modules/environment-roles/templates/shared_iam_terraform_policy_1.json.tpl

IAM permission to create new policy

---

modules/state/s3.tf

Encrypt github state bucket with CMK

---

modules/state/s3.tf

Encrypt environments state bucket with CMK
